### ISSUE TITLE
No workers exist for instance "remote-execution" platform

### ISSUE THREAD

**Issue by dhillondeep** [buildbarn/bb-deployments#17]
I am compiling a C++ bazel app with `docker-compose` but I am getting the following error. My guess is that workers are not being attached properly but I don't have enough knowledge about it. Can someone help with this error?

```ERROR: /Users/deep/Development/uptimize/rough-bazel-project/BUILD:1:1: C++ compilation of rule '//:hello-cio' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed FAILED_PRECONDITION: No workers exist for instance "remote-execution" platform {"properties":[{"name":"OSFamily","value":"Linux"},{"name":"container-image","value":"docker://marketplace.gcr.io/google/rbe-ubuntu16-04@sha256:ac36d37616b044ee77813fc7cd36607a6dc43c65357f3e2ca39f3ad723e426f6"}]}```

**Comment by EdSchouten** [comment]
If you go to http://localhost:7982/, you can see the scheduler's status page. You get a list of all known platform queues and workers attached to them. The latest Docker Compose based deployment announces workers with this platform:

```
{"properties":[{"name":"OSFamily","value":"Linux"},{"name":"container-image","value":"docker://marketplace.gcr.io/google/rbe-ubuntu16-04@sha256:6ad1d0883742bfd30eba81e292c135b95067a6706f3587498374a083b7073cb9"}]}
```

In your case you're seeing this error because Bazel is requesting that execution takes place on workers with a different SHA-256 sum in the container image. Maybe a newer version of RBE Ubuntu 16.04 came out in the meantime? As a quick workaround, you can adjust the definitions in `docker-compose/config/worker-ubuntu16-04.jsonnet`, though I suspect we may need to update the container image used in the bb-remote-execution repository as well.

**Comment by vapopov** [comment]
why did you close this issue if everyone who uses this project faces this issue?

**Comment by EdSchouten** [comment]
Because there isn't anything actionable on the bb-deployments side, right?

Every version of bazel-toolchains tends to use a different base image, and therefore different platform properties. It doesn't matter what we fill in in the configuration files on our end. It'll go stale or simply not match up with what people have configured in their Bazel workspace.

**Comment by vapopov** [comment]
that sad that the current repo just not working, I spent like 6hours at least to make it running by fixing docker-compose, then Kubernetes, the intention of it is a showcase when you clone repo , run and able to test, currently it just broken

**Comment by EdSchouten** [comment]
Be sure to submit PRs if you think there are things to improve!
