### ISSUE TITLE
Is safe to deploy Buildbarn k8s to preemptive VMs?

### ISSUE THREAD

**Issue by MikhailTymchukFT** [buildbarn/bb-deployments#36]
GKE clusters has an option to run nodes on preemptive VMs, which are much cheaper: https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms
Is it safe to deploy Buildbarn to such a cluster?

**Comment by EdSchouten** [comment]
Yes, that should be relatively safe. Just make sure that you pass in `--remote_retries` on the client side to make sure that Bazel retries build actions in case they fail due to the node disappearing.

It takes one minute for bb-scheduler to notice that a worker has disappeared: https://github.com/buildbarn/bb-remote-execution/blob/5890898b790231b69fd6c788f7cf5e33d1d69950/cmd/bb_scheduler/main.go#L85

If GKE has some kind of notification mechanism that would allow us to detect the disappearance of preemptive VMs, we could extend bb-scheduler to hook into that and immediately treat the worker as terminated, thereby causing Bazel to retry immediately.

**Comment by MikhailTymchukFT** [comment]
> If GKE has some kind of notification mechanism that would allow us to detect the disappearance of preemptive VMs, we could extend bb-scheduler to hook into that and immediately treat the worker as terminated, thereby causing Bazel to retry immediately.

Looks like [preemption notice exists for VMs](https://cloud.google.com/compute/docs/instances/preemptible#preemption-process), but [it's not handled in GKE](https://stackoverflow.com/questions/49916965/how-is-the-preemption-notice-handled).

There is a workaround which can potentially be used by Buildbarn though. It's out of scope of my original question, so want to thank you for rapid response and close the issue to keep things clean.
