### ISSUE TITLE
bb-browser in combination with kubernetes setup usability?

### ISSUE THREAD

**Issue by twuytens** [buildbarn/bb-deployments#38]
Hi,

We're currently trying out buildbarn and have a setup running on a local kubernetes cluster. What i gather from the documentation is that our Bazel client should be able to report the SHA256 hashed we need to check the CAS and AC via the Buildbarn browser.

But, for me this does not seem to work, or we're missing something obvious.

We've updated our `browserUrl` in https://github.com/buildbarn/bb-deployments/blob/master/kubernetes/config/common.yaml, and we tried adding `browserUrl: common.browserUrl,` into the config/scheduler and config/worker yaml files. Alas this does not change anything in the output of the bazel client. 

We've verified that the bb-browser is actually working and we can show some nice details when we fetch the CAS/AC ids from the kubernetes pods logs. 

It would be very useful if these things can be reported in the client somehow, so that a user does not have to look through the logs to get this detailed info. 

Any ideas on what might be the issue and how we can resolve it?

**Comment by EdSchouten** [comment]
Hoi Tim!

Yeah, all of that is not as elegant as I had hoped. Buildbarn sends back the URL in all of its responses, but Bazel only prints the URL in case of build failures due to non-zero exit codes. There is no way to make Bazel print the URLs when:
- the exit code is zero (success),
- the action as a whole failed due to a non-OK status (e.g., due an infrastructural failure).

There are certain flags you can provide on the Bazel side to enable gRPC traffic logging. You should be able to extract the URLs from the log. This is of course suboptimal, but I would like to ask you to give it a try to at least ensure that Buildbarn emits the URLs.

What's also a bit annoying is that Bazel's Build Event Stream is (almost) entirely decoupled from REv2. This means that it exposes information at Bazel targets, but doesn't give information at the build action level. There is no 1:1 correlation between those two.

**Comment by moroten** [comment]
With [`bazel build --remote_print_execution_messages=all`](https://bazel.build/reference/command-line-reference#flag--remote_print_execution_messages), the links get printed for successful remote execution.

For remote cache only, [`--remote_grpc_log`](https://bazel.build/reference/command-line-reference#flag--remote_grpc_log) in combination with https://github.com/bazelbuild/tools_remote?tab=readme-ov-file#printing-grpc-log-files will do the trick.
