### ISSUE TITLE
Provide multi-arch container images

### ISSUE THREAD

**Issue by holdenk** [buildbarn/bb-deployments#53]
I'd like to try and use buildbarn, but I've got an ARM cluster. Could using docker buildx make build barn work on ARM?

**Comment by EdSchouten** [comment]
> I'd like to try and use buildbarn, but I've got an ARM cluster. Could using docker buildx make build barn work on ARM?

I don't think `docker buildx` is going to help us here in any way. Keep in mind that Buildbarn doesn't use Docker to build container images. It uses Bazel's [rules_docker](https://github.com/bazelbuild/rules_docker). Unfortunately, rules_docker [doesn't support multi-arch containers](https://github.com/bazelbuild/rules_docker/issues/300) yet. In my opinion this is a prerequisite for offering prebuilt images, as it becomes unmanageable otherwise.

I've just gone ahead and enabled CI builds for 32- and 64-bit ARM, meaning that you can now download prebuilt executables for those platforms by going to the 'Actions' tab here on GitHub. You should now also be able to build your own ARM container images by checking out any of the bb-* repositories and running something like this:

```
bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_arm64 //cmd/bb_storage:bb_storage_container
docker tag bazel/cmd/bb_storage:bb_storage_container mytag
docker push mytag
```

I'll keep this issue report open as a reminder that we should add multi-arch container images.

**Comment by thesayyn** [comment]
@EdSchouten we started https://github.com/bazel-contrib/rules_oci as an alternative to rules_docker. Since rules_docker is basically unmaintained, I'd like to offer to migrate buildbarn from rules_docker to rules_oci which supports multi-arch out-of-the-box

**Comment by EdSchouten** [comment]
Hey! That sounds great! PRs are welcome! Probably best to start off with bb_storage?

**Comment by thesayyn** [comment]
> Hey! That sounds great! PRs are welcome! Probably best to start off with bb_storage?

Great. yeah, that sounds like a great start.

**Comment by thesayyn** [comment]
hey @EdSchouten https://github.com/buildbarn/bb-storage/pull/167 is up. looking forward to your feedback

**Comment by CaerusKaru** [comment]
@EdSchouten can this now be closed?

**Comment by EdSchouten** [comment]
Yes!
