### ISSUE TITLE
Kubernetes allowAcUpdatesForInstances Query

### ISSUE THREAD

**Issue by jonf78** [buildbarn/bb-deployments#8]
Hi,

Looking through the Kubernetes deployment files I have a query on the labels/config that are set that hoping you can clarify.

In the config/storage.yaml the following is set for the action cache
      
      "allowAcUpdatesForInstances": ["bb-event-service", "ubuntu16-04"]

My assumption (could be totally wrong :))  is that this relates to the instance label on the relevant pods ??

in the worker-ubuntu16-04.yaml I can see that the instance is set; instance: ubuntu16-04
      
in event-service.yaml there is no instance label.

Is this label required ?

Thanks
Jon

**Comment by mickael-carl** [comment]
Hi Jon!

You can find where this configuration option is defined [here](https://github.com/buildbarn/bb-storage/blob/master/pkg/proto/configuration/bb_storage/bb_storage.proto#L40). The instances themselves are indeed not defined by Kubernetes labels themselves actually, but by some other piece of configuration, for instance [this](https://github.com/buildbarn/bb-deployments/blob/master/kubernetes/config/frontend.yaml#L70) for the Kubernetes deployment, [here](https://github.com/buildbarn/bb-deployments/blob/master/bare/config/bb-storage.json#L25) for the bare deployment or [here](https://github.com/buildbarn/bb-deployments/blob/master/docker-compose/config/frontend.json#L57) for the one based on docker-compose.
This allows to assign a friendly label to scheduler instances rather than just endpoints.
Does that answer your question?
